-- MySQL Script generated by MySQL Workbench
-- Sat Dec 18 14:54:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema konference
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `konference` ;

-- -----------------------------------------------------
-- Schema konference
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `konference` DEFAULT CHARACTER SET utf8 ;
USE `konference` ;

-- -----------------------------------------------------
-- Table `konference`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `konference`.`roles` ;

CREATE TABLE IF NOT EXISTS `konference`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


INSERT INTO `konference`.`roles` (name) VALUES ("user");
INSERT INTO `konference`.`roles` (name) VALUES ("recenzent");
INSERT INTO `konference`.`roles` (name) VALUES ("admin");
INSERT INTO `konference`.`roles` (name) VALUES ("superadmin");

-- -----------------------------------------------------
-- Table `konference`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `konference`.`users` ;

CREATE TABLE IF NOT EXISTS `konference`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role`)
    REFERENCES `konference`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_roles_idx` ON `konference`.`users` (`role` ASC);


-- -----------------------------------------------------
-- Table `konference`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `konference`.`articles` ;

CREATE TABLE IF NOT EXISTS `konference`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `abstract` TEXT NOT NULL,
  `date` DATE NOT NULL DEFAULT current_timestamp(),
  `file` VARCHAR(256) NOT NULL,
  `approved` TINYINT NOT NULL DEFAULT 0,
  `author` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articles_users1`
    FOREIGN KEY (`author`)
    REFERENCES `konference`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_users1_idx` ON `konference`.`articles` (`author` ASC);


-- -----------------------------------------------------
-- Table `konference`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `konference`.`reviews` ;

CREATE TABLE IF NOT EXISTS `konference`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `article` INT NOT NULL,
  `author` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reviews_articles1`
    FOREIGN KEY (`article`)
    REFERENCES `konference`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`author`)
    REFERENCES `konference`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reviews_articles1_idx` ON `konference`.`reviews` (`article` ASC);

CREATE INDEX `fk_reviews_users1_idx` ON `konference`.`reviews` (`author` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
